# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'depend.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(730, 765)
        mainWindow.setMinimumSize(QtCore.QSize(730, 765))
        mainWindow.setMaximumSize(QtCore.QSize(730, 765))
        mainWindow.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.upper_div_line = QtWidgets.QFrame(self.centralwidget)
        self.upper_div_line.setGeometry(QtCore.QRect(171, 510, 460, 20))
        self.upper_div_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.upper_div_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.upper_div_line.setObjectName("upper_div_line")
        self.upper_hue_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.upper_hue_horizontalSlider.setGeometry(QtCore.QRect(169, 540, 350, 20))
        self.upper_hue_horizontalSlider.setStyleSheet("")
        self.upper_hue_horizontalSlider.setMaximum(255)
        self.upper_hue_horizontalSlider.setValue(255)
        self.upper_hue_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.upper_hue_horizontalSlider.setObjectName("upper_hue_horizontalSlider")
        self.upper_saturation_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.upper_saturation_horizontalSlider.setGeometry(QtCore.QRect(170, 570, 350, 16))
        self.upper_saturation_horizontalSlider.setMaximum(255)
        self.upper_saturation_horizontalSlider.setValue(255)
        self.upper_saturation_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.upper_saturation_horizontalSlider.setObjectName("upper_saturation_horizontalSlider")
        self.upper_value_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.upper_value_horizontalSlider.setGeometry(QtCore.QRect(170, 600, 350, 16))
        self.upper_value_horizontalSlider.setMaximum(255)
        self.upper_value_horizontalSlider.setValue(255)
        self.upper_value_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.upper_value_horizontalSlider.setObjectName("upper_value_horizontalSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(41, 15, 640, 480))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./assets/cv.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.upper_hue_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_hue_label.setGeometry(QtCore.QRect(80, 540, 28, 17))
        self.upper_hue_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_hue_label.setObjectName("upper_hue_label")
        self.upper_saturation_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_saturation_label.setGeometry(QtCore.QRect(80, 570, 72, 17))
        self.upper_saturation_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_saturation_label.setObjectName("upper_saturation_label")
        self.upper_value_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_value_label.setGeometry(QtCore.QRect(80, 600, 39, 17))
        self.upper_value_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_value_label.setObjectName("upper_value_label")
        self.upper_hue_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_hue_lineEdit.setGeometry(QtCore.QRect(551, 540, 81, 21))
        self.upper_hue_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_hue_lineEdit.setObjectName("upper_hue_lineEdit")
        self.upper_saturation_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_saturation_lineEdit.setGeometry(QtCore.QRect(551, 570, 81, 21))
        self.upper_saturation_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_saturation_lineEdit.setObjectName("upper_saturation_lineEdit")
        self.upper_value_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_value_lineEdit.setGeometry(QtCore.QRect(551, 600, 81, 21))
        self.upper_value_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_value_lineEdit.setObjectName("upper_value_lineEdit")
        self.upper_hsv_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_hsv_label.setGeometry(QtCore.QRect(80, 510, 79, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.upper_hsv_label.setFont(font)
        self.upper_hsv_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_hsv_label.setObjectName("upper_hsv_label")
        self.lower_hsv_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_hsv_label.setGeometry(QtCore.QRect(81, 640, 83, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lower_hsv_label.setFont(font)
        self.lower_hsv_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_hsv_label.setObjectName("lower_hsv_label")
        self.lower_value_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.lower_value_horizontalSlider.setGeometry(QtCore.QRect(171, 730, 350, 16))
        self.lower_value_horizontalSlider.setMaximum(255)
        self.lower_value_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lower_value_horizontalSlider.setObjectName("lower_value_horizontalSlider")
        self.lower_hue_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_hue_lineEdit.setGeometry(QtCore.QRect(552, 670, 81, 21))
        self.lower_hue_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_hue_lineEdit.setObjectName("lower_hue_lineEdit")
        self.lower_saturation_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.lower_saturation_horizontalSlider.setGeometry(QtCore.QRect(171, 700, 350, 16))
        self.lower_saturation_horizontalSlider.setMaximum(255)
        self.lower_saturation_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lower_saturation_horizontalSlider.setObjectName("lower_saturation_horizontalSlider")
        self.lower_value_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_value_label.setGeometry(QtCore.QRect(81, 730, 39, 17))
        self.lower_value_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_value_label.setObjectName("lower_value_label")
        self.lower_value_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_value_lineEdit.setGeometry(QtCore.QRect(552, 730, 81, 21))
        self.lower_value_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_value_lineEdit.setObjectName("lower_value_lineEdit")
        self.lower_div_line = QtWidgets.QFrame(self.centralwidget)
        self.lower_div_line.setGeometry(QtCore.QRect(171, 640, 460, 20))
        self.lower_div_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.lower_div_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lower_div_line.setObjectName("lower_div_line")
        self.lower_saturation_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_saturation_lineEdit.setGeometry(QtCore.QRect(552, 700, 81, 21))
        self.lower_saturation_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_saturation_lineEdit.setObjectName("lower_saturation_lineEdit")
        self.lower_saturation_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_saturation_label.setGeometry(QtCore.QRect(81, 700, 72, 17))
        self.lower_saturation_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_saturation_label.setObjectName("lower_saturation_label")
        self.lower_hue_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_hue_label.setGeometry(QtCore.QRect(81, 670, 28, 17))
        self.lower_hue_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_hue_label.setObjectName("lower_hue_label")
        self.lower_hue_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.lower_hue_horizontalSlider.setGeometry(QtCore.QRect(170, 670, 350, 20))
        self.lower_hue_horizontalSlider.setStyleSheet("")
        self.lower_hue_horizontalSlider.setMaximum(255)
        self.lower_hue_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lower_hue_horizontalSlider.setObjectName("lower_hue_horizontalSlider")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "HSV-Thresholding"))
        self.upper_hue_label.setText(_translate("mainWindow", "Hue"))
        self.upper_saturation_label.setText(_translate("mainWindow", "Saturation"))
        self.upper_value_label.setText(_translate("mainWindow", "Value")) 
        self.upper_hue_lineEdit.setText(_translate("mainWindow", "255"))
        self.upper_saturation_lineEdit.setText(_translate("mainWindow", "255"))
        self.upper_value_lineEdit.setText(_translate("mainWindow", "255"))
        self.upper_hsv_label.setText(_translate("mainWindow", "UPPER HSV"))
        self.lower_hsv_label.setText(_translate("mainWindow", "LOWER HSV"))
        self.lower_hue_lineEdit.setText(_translate("mainWindow", "0"))
        self.lower_value_label.setText(_translate("mainWindow", "Value"))
        self.lower_value_lineEdit.setText(_translate("mainWindow", "0"))
        self.lower_saturation_lineEdit.setText(_translate("mainWindow", "0"))
        self.lower_saturation_label.setText(_translate("mainWindow", "Saturation"))
        self.lower_hue_label.setText(_translate("mainWindow", "Hue"))
