# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'depend.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(730, 765)
        mainWindow.setMinimumSize(QtCore.QSize(730, 765))
        mainWindow.setMaximumSize(QtCore.QSize(730, 765))
        mainWindow.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.upper_div_line = QtWidgets.QFrame(self.centralwidget)
        self.upper_div_line.setGeometry(QtCore.QRect(220, 510, 460, 20))
        self.upper_div_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.upper_div_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.upper_div_line.setObjectName("upper_div_line")
        self.upper_hue_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.upper_hue_horizontalSlider.setGeometry(QtCore.QRect(218, 540, 350, 20))
        self.upper_hue_horizontalSlider.setStyleSheet("")
        self.upper_hue_horizontalSlider.setMaximum(255)
        self.upper_hue_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.upper_hue_horizontalSlider.setObjectName("upper_hue_horizontalSlider")
        self.upper_saturation_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.upper_saturation_horizontalSlider.setGeometry(QtCore.QRect(219, 570, 350, 16))
        self.upper_saturation_horizontalSlider.setMaximum(255)
        self.upper_saturation_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.upper_saturation_horizontalSlider.setObjectName("upper_saturation_horizontalSlider")
        self.upper_value_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.upper_value_horizontalSlider.setGeometry(QtCore.QRect(219, 600, 350, 16))
        self.upper_value_horizontalSlider.setMaximum(255)
        self.upper_value_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.upper_value_horizontalSlider.setObjectName("upper_value_horizontalSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(41, 15, 640, 480))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./assets/cv.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.upper_hue_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_hue_label.setGeometry(QtCore.QRect(129, 540, 28, 17))
        self.upper_hue_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_hue_label.setObjectName("upper_hue_label")
        self.upper_saturation_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_saturation_label.setGeometry(QtCore.QRect(129, 570, 72, 17))
        self.upper_saturation_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_saturation_label.setObjectName("upper_saturation_label")
        self.upper_value_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_value_label.setGeometry(QtCore.QRect(129, 600, 39, 17))
        self.upper_value_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_value_label.setObjectName("upper_value_label")
        self.upper_hue_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_hue_lineEdit.setGeometry(QtCore.QRect(600, 540, 81, 21))
        ###
        self.upper_hue_lineEdit.setReadOnly(True)
        self.upper_hue_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_hue_lineEdit.setObjectName("upper_hue_lineEdit")
        self.upper_saturation_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_saturation_lineEdit.setGeometry(QtCore.QRect(600, 570, 81, 21))
        ###
        self.upper_saturation_lineEdit.setReadOnly(True)
        self.upper_saturation_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_saturation_lineEdit.setObjectName("upper_saturation_lineEdit")
        self.upper_value_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upper_value_lineEdit.setGeometry(QtCore.QRect(600, 600, 81, 21))
        ###
        self.upper_value_lineEdit.setReadOnly(True)
        self.upper_value_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_value_lineEdit.setObjectName("upper_value_lineEdit")
        self.upper_hsv_label = QtWidgets.QLabel(self.centralwidget)
        self.upper_hsv_label.setGeometry(QtCore.QRect(129, 510, 79, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.upper_hsv_label.setFont(font)
        self.upper_hsv_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.upper_hsv_label.setObjectName("upper_hsv_label")
        self.lower_hsv_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_hsv_label.setGeometry(QtCore.QRect(130, 640, 83, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lower_hsv_label.setFont(font)
        self.lower_hsv_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_hsv_label.setObjectName("lower_hsv_label")
        self.lower_value_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.lower_value_horizontalSlider.setGeometry(QtCore.QRect(220, 730, 350, 16))
        self.lower_value_horizontalSlider.setMaximum(255)
        self.lower_value_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lower_value_horizontalSlider.setObjectName("lower_value_horizontalSlider")
        self.lower_hue_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_hue_lineEdit.setGeometry(QtCore.QRect(601, 670, 81, 21))
        ###
        self.lower_hue_lineEdit.setReadOnly(True)
        self.lower_hue_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_hue_lineEdit.setObjectName("lower_hue_lineEdit")
        self.lower_saturation_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.lower_saturation_horizontalSlider.setGeometry(QtCore.QRect(220, 700, 350, 16))
        self.lower_saturation_horizontalSlider.setMaximum(255)
        self.lower_saturation_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lower_saturation_horizontalSlider.setObjectName("lower_saturation_horizontalSlider")
        self.lower_value_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_value_label.setGeometry(QtCore.QRect(130, 730, 39, 17))
        self.lower_value_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_value_label.setObjectName("lower_value_label")
        self.lower_value_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_value_lineEdit.setGeometry(QtCore.QRect(601, 730, 81, 21))
        ###
        self.lower_value_lineEdit.setReadOnly(True)
        self.lower_value_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_value_lineEdit.setObjectName("lower_value_lineEdit")
        self.lower_div_line = QtWidgets.QFrame(self.centralwidget)
        self.lower_div_line.setGeometry(QtCore.QRect(220, 640, 460, 20))
        self.lower_div_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.lower_div_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lower_div_line.setObjectName("lower_div_line")
        self.lower_saturation_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lower_saturation_lineEdit.setGeometry(QtCore.QRect(601, 700, 81, 21))
        ###
        self.lower_saturation_lineEdit.setReadOnly(True)
        self.lower_saturation_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_saturation_lineEdit.setObjectName("lower_saturation_lineEdit")
        self.lower_saturation_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_saturation_label.setGeometry(QtCore.QRect(130, 700, 72, 17))
        self.lower_saturation_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_saturation_label.setObjectName("lower_saturation_label")
        self.lower_hue_label = QtWidgets.QLabel(self.centralwidget)
        self.lower_hue_label.setGeometry(QtCore.QRect(130, 670, 28, 17))
        self.lower_hue_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.lower_hue_label.setObjectName("lower_hue_label")
        self.lower_hue_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.lower_hue_horizontalSlider.setGeometry(QtCore.QRect(219, 670, 350, 20))
        self.lower_hue_horizontalSlider.setStyleSheet("")
        self.lower_hue_horizontalSlider.setMaximum(255)
        self.lower_hue_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lower_hue_horizontalSlider.setObjectName("lower_hue_horizontalSlider")
        self.vertical_div_line = QtWidgets.QFrame(self.centralwidget)
        self.vertical_div_line.setGeometry(QtCore.QRect(110, 510, 3, 235))
        self.vertical_div_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_div_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_div_line.setObjectName("vertical_div_line")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setGeometry(QtCore.QRect(40, 510, 53, 17))
        self.camera_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.camera_label.setObjectName("camera_label")
        self.path_label = QtWidgets.QLabel(self.centralwidget)
        self.path_label.setGeometry(QtCore.QRect(40, 530, 35, 17))
        self.path_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.path_label.setObjectName("path_label")
        self.camera_path_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.camera_path_lineEdit.setGeometry(QtCore.QRect(40, 560, 51, 21))
        self.camera_path_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.camera_path_lineEdit.setObjectName("camera_path_lineEdit")
        self.test_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.test_pushButton.setGeometry(QtCore.QRect(40, 600, 51, 25))
        self.test_pushButton.setObjectName("test_pushButton")
        self.reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_pushButton.setGeometry(QtCore.QRect(40, 640, 51, 25))
        self.reset_pushButton.setObjectName("reset_pushButton")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.upper_hue_label.setText(_translate("mainWindow", "Hue"))
        self.upper_saturation_label.setText(_translate("mainWindow", "Saturation"))
        self.upper_value_label.setText(_translate("mainWindow", "Value"))
        self.upper_hue_lineEdit.setText(_translate("mainWindow", "0"))
        self.upper_saturation_lineEdit.setText(_translate("mainWindow", "0"))
        self.upper_value_lineEdit.setText(_translate("mainWindow", "0"))
        self.upper_hsv_label.setText(_translate("mainWindow", "UPPER HSV"))
        self.lower_hsv_label.setText(_translate("mainWindow", "LOWER HSV"))
        self.lower_hue_lineEdit.setText(_translate("mainWindow", "0"))
        self.lower_value_label.setText(_translate("mainWindow", "Value"))
        self.lower_value_lineEdit.setText(_translate("mainWindow", "0"))
        self.lower_saturation_lineEdit.setText(_translate("mainWindow", "0"))
        self.lower_saturation_label.setText(_translate("mainWindow", "Saturation"))
        self.lower_hue_label.setText(_translate("mainWindow", "Hue"))
        self.camera_label.setText(_translate("mainWindow", "Camera"))
        self.path_label.setText(_translate("mainWindow", "path:"))
        self.camera_path_lineEdit.setText(_translate("mainWindow", "0"))
        self.test_pushButton.setText(_translate("mainWindow", "Test"))
        self.reset_pushButton.setText(_translate("mainWindow", "Reset"))
